name: FastAPIProject
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_3
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_3
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.12.12=h2bfc596_1
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py312hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py312hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - certifi==2025.11.12
      - click==8.3.1
      - dnspython==2.8.0
      - email-validator==2.3.0
      - fastapi==0.124.0
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.6.0
      - fastar==0.8.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - idna==3.11
      - jinja2==3.1.6
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pyyaml==6.0.3
      - rich==14.2.0
      - rich-toolkit==0.17.0
      - rignore==0.7.6
      - sentry-sdk==2.47.0
      - shellingham==1.5.4
      - starlette==0.50.0
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websockets==15.0.1
prefix: /Users/alfredlv/miniconda3/envs/FastAPIProject
